group/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

# from logger.views import delete_instance


app_name = 'group'

urlpatterns = [

    url(r'^groups/$', views.group_list, name='groups_list'),
    url(r'^group_detail/(?P<group_id>[0-9]+)$', views.group_detail, name='group_detail'),
    url(r'^add_group/$', views.edit_group, name='add_group'),
    url(r'^edit_group/(?P<group_id>[0-9]+)$', views.edit_group, name='edit_group'),
    url(r'^deletion/$', views.remove_group, name='deletion'),
    url(r'^remove_group/(?P<group_id>[0-9]+)/', views.remove_group, kwargs={'instance_type': 2}, name='remove_group'),

]

main/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from main.views import logout
from . import views
from group.views import group_list

app_name = 'main'

urlpatterns = [

    url(r'^$', group_list, name='index'),
    url(r'^logout/$', logout, name='logout'),

]

py_dev_ib/urls.py
from django.contrib import admin
from django.conf.urls import url, include

from group.views import group_list


handler404 = 'django_junior.views.custom_404_server_error'
handler500 = 'django_junior.views.custom_500_server_error'


urlpatterns = [

    url(r'^$', group_list, name='index'),

    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/', include(admin.site.urls), name="admin"),

    url(r'^main/', include('main.urls')),
    url(r'^students/', include('students.urls')),
    url(r'^group/', include('group.urls')),
    url(r'^logger/', include('logger.urls')),

]

students/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from students import views

app_name = 'students'

urlpatterns = [

    url(r'^students/$', views.student_list, name='students_list'),
    url(r'^add_student/$', views.edit_student, name='add_student'),
    url(r'^edit_student/(?P<student_id>[0-9]+)$', views.edit_student, name='edit_student'),
    url(r'^deletion/$', views.remove_student, name='deletion'),
    url(r'^remove_student/(?P<student_id>[0-9]+)/', views.remove_student, kwargs={'instance_type': 1}, name='remove_student'),

]

group/models.py
# -*- coding: utf-8 -*-

from django.db import models


class Group(models.Model):

    class Meta:
        db_table = 'group'
        verbose_name = 'Group'
        verbose_name_plural = 'Groups'

    name = models.CharField(verbose_name='Название группы', max_length=50)  # Название группы
    captain = models.ForeignKey('students.Student',
                                on_delete=models.SET_NULL,
                                verbose_name='Староста группы',
                                related_name="groups",
                                null=True,
                                blank=True)  # Староста группы

    def __str__(self):
        return u"{0}".format(self.name)

group/forms.py
# -*- coding: utf-8 -*-


import crispy_forms.bootstrap as bs3

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Submit, HTML
from django import forms
from group.models import Group
from students.models import Student


class GroupForm(forms.ModelForm):

    name = forms.CharField(label='Имя группы')  # Имя группы
    captain = forms.ModelChoiceField(Student.objects.none(), label="Староста группы",
                                     required=False, empty_label="")  # Староста группы

    class Meta:
        model = Group
        fields = [
            'name',
            'captain',
        ]

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.form_class = 'form-horizontal'
    helper.label_class = 'col-sm-7'
    helper.field_class = 'col-sm-7'
    helper.layout = Layout(

            Field('name', css_class='input-sm'),
            bs3.FieldWithButtons('captain',
                 bs3.FieldWithButtons(HTML("""{% if form.instance.captain_id %}
                                              <a id="student_url" href="{% url 'students:edit_student' form.instance.captain_id %}"
                                              type="submit" class="btn btn-success edit_counterparty">
                                              <span class="glyphicon glyphicon-pencil" style="color:white;">
                                              </span> Ред.</a>
                                              {% endif %}""")),
                  wrapper_class='col-xs-3 col-sm-3 col-md-3 col-lg-3',
                  placeholder="Группа",
                  ),

            bs3.FormActions(Submit('purchase', 'Сохранить', css_class='btn btn-success'))
    )

    def __init__(self, *args, **kwargs):
        super(GroupForm, self).__init__(*args, **kwargs)

        try:
            self.fields['captain'].queryset = Student.objects.filter(group=kwargs['instance'])
        except:
            self.fields['captain'].queryset = Student.objects.all()

group/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.core.urlresolvers import reverse
from django.views.decorators.csrf import csrf_exempt

from group.forms import GroupForm
from group.models import Group
from logger.forms import TrueFalseForm
from students.models import Student


def group_list(request):
    group_list = Group.objects.all().order_by('name')
    dict = {}
    for group in group_list:
        count = Student.objects.filter(group=group.id).count()
        dict[group.id]=count
    return render(request, 'group/group_list.html', {
        'group_list': group_list,
        'dict': dict,
    })


def group_detail(request, group_id):
    student_list = Student.objects.filter(group=group_id).order_by('name')
    return render(request, 'group/group_detail.html', {'student_list': student_list})


@login_required(login_url='/accounts/login/')
def edit_group(request, group_id=None):
    if request.method == 'POST':
        if group_id is None:
            form = GroupForm(request.POST)
        else:
            edit_group = get_object_or_404(Group, id=group_id)
            form = GroupForm(request.POST, instance=edit_group)
        if form.is_valid():
            form.save()
            return redirect(reverse('group:groups_list', args={}))
    else:
        if group_id is None:
            form = GroupForm()
        else:
            group = get_object_or_404(Group, id=group_id)
            form = GroupForm(instance=group)
        return render(request, 'group/edit_group.html', {
            'form': form,
        })


@csrf_exempt
@login_required(login_url='/accounts/login/')
def remove_group(request, group_id, instance_type):
    if instance_type == 2:
        instance = get_object_or_404(Group, pk=group_id)
    else:
        raise Http404
    if request.method == 'POST':
        form = TrueFalseForm(request.POST)
        if form.is_valid():
            choice = form.cleaned_data['choice']
            if choice:
                instance.delete()
            return redirect(reverse('group:groups_list', args={}))
    else:
        form = TrueFalseForm()
    data = dict(form=form, instance_id=group_id, instance=instance, instance_type=instance_type)
    return render_to_response('logger/deletion.html', data)

group/templates/group/edit_group.html
{% extends 'main/base.html' %}


{% load staticfiles %}


{% load crispy_forms_tags %}


{% block title %}Группа{% endblock %}


{% block meta %}
    <style>
        .table tr td {
            font-size: 14px;
            font-family: Arial, Helvetica, sans-serif;
        }
    </style>

    <script>

    </script>
{% endblock %}


{% block content %}
    <div class="container">
        <div class="col-lg-12">
            <div class="row">
                <h3 style="text-align: center">Группа</h3>
                {% crispy form %}
            </div>
        </div>
    </div>
{% endblock %}

{% block meta_end_body %}

  <script>

  $(document).ready(function () {
      change_url_rdit();
  });

  $('#id_captain').on('change', function () {
       change_url_rdit();
  });

  function change_url_rdit() {
      let url_edit = $('#student_url').attr('href').split('/');
      let url_edit_last_index = url_edit.slice(-1).toString().split('?');
      url_edit_last_index[0] = $('#id_captain').val();
      url_edit[url_edit.length-1] = url_edit_last_index.join('?');
      $('#student_url').attr('href', url_edit.join('/'));

  }

  </script>


{% endblock %}

group/templates/group/group_detail.html
{% extends 'main/base.html' %}

{% load staticfiles %}

{% load i18n %}

{% block title %} Студенты {% endblock %}


{% block content %}


  <div class="table-wrapper">
    <h3>Студенты</h3>
    <a style="float: left" href="{%  url 'students:add_student' %}"
                         type="button" class="btn btn-default">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Добавить </a>
    <br>
    <br>

    <table border="0" rules="all" cellpadding="10" width='50%'>
      <thead>
        <tr>
          <th>П/П</th>
          <th>ФИО</th>
          <th>Студенческий билет</th>
          <th>Группа</th>
          <th>День рождения</th>
          <th></th>
        </tr>
      </thead>
        <tbody>
          {% for student in student_list %}
            <tr>
              <td>{{ forloop.counter }}</td>
              <td>{{ student.get_name }}</td>
              <td>{{ student.student_card }}</td>
              <td>{{ student.group.name }}</td>
              <td>{{ student.date_of_birth }}</td>
              <td>
                <a href="{% url 'students:edit_student' student.id %}"
                   class="btn-floating waves-effect waves-light white z-depth-0">
                  <i class="material-icons" style="color: #1643b8;">Редактировать</i></a> /

                <a href="{% url 'students:remove_student' student.id %}"
                   onclick="return confirm('Вы уверены ?')"
                   class="btn-floating waves-effect waves-light white z-depth-0">
                  <i class="material-icons" style="color: #F44336;">Удалить</i></a>

              </td>
            </tr>
          {% endfor %}
        </tbody>
    </table>
  </div>

{% endblock %}

group/templates/group/group_list.html
{% extends 'main/base.html' %}

{% load staticfiles %}

{% load i18n %}

{% block title %} Группы {% endblock %}


{% block content %}
<div class="table-wrapper">
  <h3>Группы</h3>

  <a style="float: left" href="{%  url 'group:add_group' %}"
                         type="button" class="btn btn-default">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Добавить </a>
  <br>
  <br>

  <table border="0" rules="all" cellpadding="10" width='50%'>
    <thead>
      <tr>
          <th>П/П</th>
          <th>Группа</th>
          <th>Количество студентов</th>
          <th>Староста</th>
          <th></th>
      </tr>
    </thead>
    <tbody>
      {% for group in group_list %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td><a class="id_back_counterparty" href="{% url 'group:group_detail' group.id %}">{{ group.name }}</a></td>
          <td>
            {% for key, val in dict.items %}
              {% if group.id == key %}
                {{ val }}
              {% endif %}
            {% endfor %}
          </td>
          <td>{{ group.captain.get_name }}</td>
          <td>
            <a href="{% url 'group:edit_group' group.id %}"
               class="btn-floating waves-effect waves-light white z-depth-0">
              <i style="color: #1643b8;">Редактировать</i></a> /
            <a href="{% url 'group:remove_group' group.id %}"
               class="btn-floating waves-effect waves-light white z-depth-0">
              <i style="color: #F44336;">Удалить</i></a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}