main/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from main.views import logout
from . import views
from group.views import group_list

app_name = 'main'

urlpatterns = [

    url(r'^$', group_list, name='index'),
    url(r'^logout/$', logout, name='logout'),

]

py_dev_ib/urls.py
from django.contrib import admin
from django.conf.urls import url, include

from group.views import group_list


handler404 = 'django_junior.views.custom_404_server_error'
handler500 = 'django_junior.views.custom_500_server_error'


urlpatterns = [

    url(r'^$', group_list, name='index'),

    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/', include(admin.site.urls), name="admin"),

    url(r'^main/', include('main.urls')),
    url(r'^students/', include('students.urls')),
    url(r'^group/', include('group.urls')),
    url(r'^logger/', include('logger.urls')),

]

students/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from students import views

app_name = 'students'

urlpatterns = [

    url(r'^students/$', views.student_list, name='students_list'),
    url(r'^add_student/$', views.edit_student, name='add_student'),
    url(r'^edit_student/(?P<student_id>[0-9]+)$', views.edit_student, name='edit_student'),
    url(r'^deletion/$', views.remove_student, name='deletion'),
    url(r'^remove_student/(?P<student_id>[0-9]+)/', views.remove_student, kwargs={'instance_type': 1}, name='remove_student'),

]

students/models.py
# -*- coding: utf-8 -*-

from django.db import models


class Student(models.Model):

    class Meta:
        db_table = 'students'
        verbose_name = 'Student'
        verbose_name_plural = 'Students'

    name = models.CharField(verbose_name='Имя', max_length=50)  # Имя
    surname = models.CharField(verbose_name='Фамилия', max_length=50)  # Фамилия
    father_name = models.CharField(verbose_name='Отчество', blank=True, max_length=50)  # Отчество
    date_of_birth = models.DateField(verbose_name='День рождения', default=0)  # День рождения
    student_card = models.CharField(verbose_name='Студенческий билет', max_length=50)  # Студенческий билет
    group = models.ForeignKey('group.Group', null=True, blank=True, verbose_name='Группа студента')  # Группа студента

    def get_name(self):
        return "%s %s %s" % (self.surname, self.name, self.father_name)

    def __str__(self):
        return u"{0} {1} {2}".format(self.surname, self.name, self.father_name, )

students/forms.py
# -*- coding: utf-8 -*-


import crispy_forms.bootstrap as bs3

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Submit, HTML
from django import forms
# from django.forms import SelectDateWidget
from django.forms.extras import SelectDateWidget

from students.models import Student
from group.models import Group



class StudentForm(forms.ModelForm):

    date_of_birth = forms.DateField(
        widget=forms.TextInput(attrs={'type': 'date'}),
                                     required=False, label="День рождения")  # День рождения
    group = forms.ModelChoiceField(Group.objects.all(), label="Группа",
                                   required=False, empty_label="")  # Группа

    class Meta:
        model = Student
        fields = [
            'name',
            'surname',
            'father_name',
            'student_card',
            'group',
            'date_of_birth'
        ]

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.form_class = 'form-horizontal'
    helper.label_class = 'col-sm-7'
    helper.field_class = 'col-sm-7'
    helper.layout = Layout(

        Field('name', css_class='input-sm'),
        Field('surname', css_class='input-sm'),
        Field('father_name', css_class='input-sm'),
        Field('student_card', css_class='input-sm'),
        Field('date_of_birth', datadatepicker='datepicker'),
        bs3.FieldWithButtons('group',
             bs3.FieldWithButtons(HTML("""{% if form.instance.group_id %}
                                          <a  id="group_url" href="{% url 'group:edit_group' form.instance.group_id %}"
                                          type="submit" class="btn btn-success edit_counterparty">
                                          <span class="glyphicon glyphicon-pencil" style="color:white;">
                                          </span> Ред.</a>
                                          {% endif %}""")),
              wrapper_class='col-xs-3 col-sm-3 col-md-3 col-lg-3',
              placeholder="Студент",
              ),

        bs3.FormActions(Submit('purchase', 'Сохранить', css_class='btn btn-success'))
    )

students/views.py
# -*- coding: utf-8 -*-

from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404, render_to_response
from django.views.decorators.csrf import csrf_exempt

from logger.forms import TrueFalseForm
from students.models import Student
from students.forms import StudentForm


def student_list(request):
    student_list = Student.objects.all().order_by('name')
    return render(request, 'students/student_list.html', {'student_list': student_list})


@login_required(login_url='/accounts/login/')
def edit_student(request, student_id=None):
    if request.method == 'POST':
        if student_id is None:
            form = StudentForm(request.POST)
        else:
            edit_student = get_object_or_404(Student, id=student_id)
            form = StudentForm(request.POST, instance=edit_student)
        if form.is_valid():
            form.save()
            return redirect(reverse('students:students_list', args={}))
    else:
        if student_id is None:
            form = StudentForm()
        else:
            student = get_object_or_404(Student, id=student_id)
            form = StudentForm(instance=student)
        return render(request, 'students/edit_student.html', {
            'form': form,
        })


@csrf_exempt
@login_required(login_url='/accounts/login/')
def remove_student(request, student_id, instance_type):
    if instance_type == 1:
        instance = get_object_or_404(Student, pk=student_id)
    else:
        raise Http404
    if request.method == 'POST':
        form = TrueFalseForm(request.POST)
        if form.is_valid():
            choice = form.cleaned_data['choice']
            if choice:
                instance.delete()
            return redirect(reverse('students:students_list', args={}))
    else:
        form = TrueFalseForm()
    data = dict(form=form, instance_id=student_id, instance=instance, instance_type=instance_type)
    return render_to_response('logger/deletion.html', data)

students/templates/students/edit_student.html
{% extends 'main/base.html' %}


{% load staticfiles %}


{% load crispy_forms_tags %}


{% block title %}Студент{% endblock %}


{% block meta %}
    <style>
        .table tr td {
            font-size: 14px;
            font-family: Arial, Helvetica, sans-serif;
        }
    </style>

    <script>

    </script>

{% endblock %}


{% block content %}

    <div class="container">
        <div class="col-lg-12">
            <div class="row">
                <h3 style="text-align: center">Студент</h3>
                {% crispy form %}
            </div>
        </div>
    </div>
{% endblock %}

{% block meta_end_body %}

<script>

  $(document).ready(function () {
      change_url_rdit();
  });

  $('#id_group').on('change', function () {
       change_url_rdit();
  });

  function change_url_rdit() {
      let url_edit = $('#group_url').attr('href').split('/');
      let url_edit_last_index = url_edit.slice(-1).toString().split('?');
      url_edit_last_index[0] = $('#id_group').val();
      url_edit[url_edit.length-1] = url_edit_last_index.join('?');
      $('#group_url').attr('href', url_edit.join('/'));

  }

</script>

{% endblock %}

students/templates/students/student_list.html
{% extends 'main/base.html' %}

{% load staticfiles %}

{% load i18n %}

{% block title %} Студенты {% endblock %}


{% block content %}


  <div class="table-wrapper">
    <h3>Студенты</h3>
    <a style="float: left" href="{%  url 'students:add_student' %}"
                         type="button" class="btn btn-default">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Добавить </a>
    <br>
    <br>

    <table border="0" rules="all" cellpadding="10" width='50%'>
      <thead>
        <tr>
          <th>П/П</th>
          <th>ФИО</th>
          <th>Студенческий билет</th>
          <th>Группа</th>
          <th>День рождения</th>
          <th></th>
        </tr>
      </thead>
        <tbody>
          {% for student in student_list %}
            <tr>
              <td>{{ forloop.counter }}</td>
              <td>{{ student.get_name }}</td>
              <td>{{ student.student_card }}</td>
              <td>{{ student.group.name }}</td>
              <td>{{ student.date_of_birth }}</td>
              <td>
                <a href="{% url 'students:edit_student' student.id %}"
                   class="btn-floating waves-effect waves-light white z-depth-0">
                  <i style="color: #1643b8;">Редактировать</i></a> /
                <a href="{% url 'students:remove_student' student.id %}"
                   class="btn-floating waves-effect waves-light white z-depth-0">
                  <i style="color: #F44336;">Удалить</i></a>

              </td>
            </tr>
          {% endfor %}
        </tbody>
    </table>
  </div>

{% endblock %}