group/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

# from logger.views import delete_instance


app_name = 'group'

urlpatterns = [

    url(r'^groups/$', views.group_list, name='groups_list'),
    url(r'^group_detail/(?P<group_id>[0-9]+)$', views.group_detail, name='group_detail'),
    url(r'^add_group/$', views.edit_group, name='add_group'),
    url(r'^edit_group/(?P<group_id>[0-9]+)$', views.edit_group, name='edit_group'),
    url(r'^deletion/$', views.remove_group, name='deletion'),
    url(r'^remove_group/(?P<group_id>[0-9]+)/', views.remove_group, kwargs={'instance_type': 2}, name='remove_group'),

]

main/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from main.views import logout
from . import views
from group.views import group_list

app_name = 'main'

urlpatterns = [

    url(r'^$', group_list, name='index'),
    url(r'^logout/$', logout, name='logout'),

]

py_dev_ib/urls.py
from django.contrib import admin
from django.conf.urls import url, include

from group.views import group_list


handler404 = 'django_junior.views.custom_404_server_error'
handler500 = 'django_junior.views.custom_500_server_error'


urlpatterns = [

    url(r'^$', group_list, name='index'),

    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/', include(admin.site.urls), name="admin"),

    url(r'^main/', include('main.urls')),
    url(r'^students/', include('students.urls')),
    url(r'^group/', include('group.urls')),
    url(r'^logger/', include('logger.urls')),

]

students/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from students import views

app_name = 'students'

urlpatterns = [

    url(r'^students/$', views.student_list, name='students_list'),
    url(r'^add_student/$', views.edit_student, name='add_student'),
    url(r'^edit_student/(?P<student_id>[0-9]+)$', views.edit_student, name='edit_student'),
    url(r'^deletion/$', views.remove_student, name='deletion'),
    url(r'^remove_student/(?P<student_id>[0-9]+)/', views.remove_student, kwargs={'instance_type': 1}, name='remove_student'),

]

main/views.py
from django.shortcuts import render_to_response


from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect


@login_required
def logout(request):
    auth_logout(request)
    return HttpResponseRedirect(reverse('main:index', args=()))


def custom_404_server_error(request):
    """
    Call 404.html
    """
    response = render_to_response('main/404.html')
    response.status_code = 404
    return response


def custom_500_server_error(request):
    """
    Call 500.html
    """
    response = render_to_response('main/500.html')
    response.status_code = 500
    return response

main/templates/main/base.html
{% load staticfiles %}

<!DOCTYPE html>

<html lang="ru">

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="lang" content="ru">

  <title>{% spaceless %}{% block title %} Статьи {% endblock %}{% endspaceless %}</title>

  <meta name="description" content="{% spaceless %}{% block description %}{% endblock %}{% endspaceless %}">
  <meta name="keywords" content="{% spaceless %}{% block keywords %}{% endblock %}{% endspaceless %}">

  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  {% block head_page %}{% endblock %}

</head>

  <body>

    <div class="hidden" id="csrf_token">
      {% csrf_token %}
    </div>

    {% block header %}

      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav" >
              <li role="presentation" class={% block active_main %}{% endblock active_main %}>
                <a href="{% url 'group:groups_list' %}"><span class="glyphicon glyphicon-th"></span> Группы</a></li>
              <li><a href="{% url 'students:students_list' %}"><span class="glyphicon glyphicon-user"></span> Студенты</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="navbar-nav"><a href="/accounts/login/">
                <span class=" glyphicon glyphicon-log-in"></span> Sign in</a></li>
              <li class="navbar-nav"><a href="{% url 'main:logout' %}">
                <span class="glyphicon glyphicon-log-out"></span> Sign out</a></li>
              <li><a href="{% url 'admin:index' %}"><span class="glyphicon glyphicon-cog"></span> Admin</a></li>

            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>

    {% endblock %}

    <div class="container-fluid">
      <div class="jumbotron" style="background:rgba(255,255,255,0.5);">
        {% block content %}{% endblock content %}
      </div>
    </div>

  <script src="{% static 'js/bootstrap.js' %}"></script>
  <script src="{% static 'js/jquery-1.12.2.min.js' %}"></script>
  <script src="{% static 'js/jquery.backstretch.min.js' %}"></script>


  {% block meta_end_body %}{% endblock %}

  <div>
    <a href="{{ ADMIN_MEDIA_URL }}">путь к admin media</a><br><br>
  </div>

  </body>

</html>

main/templates/main/tag.html
<a href="{{ admin_url }}">{{ link }}</a>